### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by abulte** [adriangb/asyncpg-trek#2]
Hi,

Thanks for this lib! I like the minimalist approach and [put it to use](https://github.com/etalab/udata-hydra/pull/42).

It would be nice to have this package published on pypi. I see your CI should do it but it seems broken.

Thanks again!

**Comment by adriangb** [comment]
Thanks, will try to fix today

**Comment by adriangb** [comment]
Done!

**Comment by abulte** [comment]
Awesome, thanks!
