### ISSUE TITLE
Default schema for the migrations table

### ISSUE THREAD

**Issue by euri10** [adriangb/asyncpg-trek#7]
Currently the public schema is the default for creating the migrations table, there doesnt seem to be a way to create it elsewhere.

I'd be tempted to say it is a bad idea because:
1. you may have another migrations table inside that public schema and it leaves you no options.
2. running execute on a schema where there is no migrations table will fail

What do you think of this: asyncpg-trek creates its own schema to handle migrations, and uses a migrations table inside it, low chances of conflicts, and you are able to run migrations on others schema, asyncpg-trek always knows where to find its migrations table

**Comment by adriangb** [comment]
> What do you think of this: asyncpg-trek creates its own schema to handle migrations

One huge issue: you're not always allowed to create your own schemas on certain hosted Postgres offerings. I think it should be an _option_ but not the default.

**Comment by euri10** [comment]
oh I didn't know that, how people can live without ?
but yeah so optional makes more sense in that case you're right.

**Comment by adriangb** [comment]
PR welcome 😄
